import { defineNuxtConfig } from "nuxt/config";

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
    modules: [
        "@nuxt/image",
        "nuxt-security",
        "@nuxt/fonts",
        "@nuxtjs/tailwindcss",
        "@vueuse/nuxt",
        "@nuxt/icon",
        "@nuxtjs/seo",
    ],
    compatibilityDate: "2024-04-03",
    devtools: { enabled: true },
    // Disable automatic component imports (for readability)
    components: false,
    robots: {
        blockNonSeoBots: true,
        disallow: [
            "AI2Bot",
            "Ai2Bot-Dolma",
            "Amazonbot",
            "anthropic-ai",
            "Applebot",
            "Applebot-Extended",
            "Bytespider",
            "CCBot",
            "ChatGPT-User",
            "Claude-Web",
            "ClaudeBot",
            "cohere-ai",
            "Diffbot",
            "FacebookBot",
            "facebookexternalhit",
            "FriendlyCrawler",
            "Google-Extended",
            "GoogleOther",
            "GoogleOther-Image",
            "GoogleOther-Video",
            "GPTBot",
            "iaskspider/2.0",
            "ICC-Crawler",
            "ImagesiftBot",
            "img2dataset",
            "ISSCyberRiskCrawler",
            "Kangaroo Bot",
            "Meta-ExternalAgent",
            "Meta-ExternalFetcher",
            "OAI-SearchBot",
            "omgili",
            "omgilibot",
            "PerplexityBot",
            "PetalBot",
            "Scrapy",
            "Sidetrade indexer bot",
            "Timpibot",
            "VelenPublicWebCrawler",
            "Webzio-Extended",
            "YouBot",
        ],
    },
    future: {
        compatibilityVersion: 4,
    },
    image: {
        domains: ["images.pexels.com"],
    },
    nitro: {
        preset: "bun",
        minify: true,
        prerender: {
            failOnError: true,
        },
    },
});
